// Generated by CoffeeScript 1.6.3
(function() {
  var data, options;

  options = {
    asBars: {
      series: {
        stack: true,
        group: true,
        groupInterval: 1,
        bars: {
          show: true,
          align: 'center',
          lineWidth: 1
        }
      },
      shadowSize: 0
    },
    asLines: {
      series: {
        stack: true,
        group: true,
        groupInterval: 1,
        lines: {
          show: true,
          fill: true,
          lineWidth: 1
        },
        shadowSize: 0
      }
    },
    asTimeSeries: {
      xaxis: {
        mode: 'time',
        timezone: 'browser'
      },
      series: {
        stack: true,
        group: true,
        groupInterval: 24 * 60 * 60 * 1000,
        bars: {
          show: true,
          align: 'center',
          lineWidth: 0,
          barWidth: 24 * 60 * 60 * 1000
        }
      },
      shadowSize: 0
    }
  };

  data = [
    {
      x: function(n) {
        return n;
      },
      y: function(n) {
        return Math.random() * 10 - 5.;
      }
    }, {
      x: function(n) {
        return n;
      },
      y: function(n) {
        return Math.random() * 10;
      }
    }, {
      x: function(n) {
        var d;
        d = new Date();
        d.setDate(n + Math.random());
        return d;
      },
      y: function(n) {
        return Math.random() * 10 - 5.;
      }
    }
  ].map(function(f) {
    return ['A', 'B', 'C', 'D'].map(function(s) {
      var _i, _results;
      return {
        label: s,
        data: (function() {
          _results = [];
          for (_i = 1; _i <= 30; _i++){ _results.push(_i); }
          return _results;
        }).apply(this).map(function(n) {
          return [f.x(n), f.y(n)];
        })
      };
    });
  });

  $.plot($('#placeholder1'), $.extend(true, [], data[0]), options.asBars);

  $.plot($('#placeholder2'), $.extend(true, [], data[1]), options.asLines);

  $.plot($('#placeholder3'), $.extend(true, [], data[2]), options.asTimeSeries);

}).call(this);

/*
//@ sourceMappingURL=example.map
*/
